:level-9 {:english {:level-title "Level 9"
                    :paragraph-1 (str "Human " applicant-name ", a ")
                    :paragraph-1.1 "collection binding"
                    :paragraph-1.2 " binds a single variable to multiple values passed in as a collection. Using the "
                    :paragraph-1.3 "[variable ...]"
                    :paragraph-1.4 " syntax this can be used to ask \"or\" questions such as what is the capacity and address associated with farms named either 'Power From the People' or 'The Big Wheel'?"
                    :paragraph-2 "(d/q '[:find (pull ?e [:farm/capacity :farm/address])\n       :in $ [?farm-name ...]\n       :where [?e :farm/name ?farm-name]] db [\"Power From the People\" \"The Big Wheel\"])"
                    :paragraph-3 "Modify the query to use the author-ids as an input to the query in order to retrieve the "
                    :paragraph-3.1 "first"
                    :paragraph-3.2 " and "
                    :paragraph-3.3 "last"
                    :paragraph-3.4 " names of both authors."
                    :paragraph-4 "You may now continue to level 10."}
          :portuguese {:level-title "Nível 9"
                       :paragraph-1 (str "Humano " applicant-name ", uma ")
                       :paragraph-1.1 "Collection Binding"
                       :paragraph-1.2 " vincula uma única variável a vários valores passados como uma coleção. Usando a "
                       :paragraph-1.3 "[variable ...]"
                       :paragraph-1.4 " sintaxe isso pode ser usado para fazer \"or\" perguntas, como: Qual é a capacidade e o endereço associado a fazendas chamadas 'Power From the people' ou 'The Big Wheel'?"
                       :paragraph-2 "(d/q '[:find (pull ?e [:farm/capacity :farm/address])\n       :in $ [?farm-name ...]\n       :where [?e :farm/name ?farm-name]] db [\"Power From the People\" \"The Big Wheel\"])"
                       :paragraph-3 "Modifique a query para usar os author-ids como uma entrada para a query, a fim de recuperar os "
                       :paragraph-3.1 "primeiros"
                       :paragraph-3.2 " e "
                       :paragraph-3.3 "últimos"
                       :paragraph-3.4 " nomes de ambos os autores."
                       :paragraph-4 "Você pode seguir para o nível 10."}
          :spanish {:level-title "Nivel 9"
                    :paragraph-1 (str "Humano" applicant-name "una")
                    :paragraph-1.1 "Collection Binding (Unión de Conexiones)"
                    :paragraph-1.2 " une una única variable a varios valores pasados como una colección. Usando la sintaxis"
                    :paragraph-1.3 "[variable ...]"
                    :paragraph-1.4 " Esto puede ser usado para hacer preguntas del tipo \"or\" tales como: ¿Cuál es la capacidad y dirección asociada con granjas llamadas ya sea 'Power From the People' or 'The Big Wheel'?"
                    :paragraph-2 "(d/q '[:find (pull ?e [:farm/capacity :farm/address])\n       :in $ [?farm-name ...]\n       :where [?e :farm/name ?farm-name]] db [\"Power From the People\" \"The Big Wheel\"])"
                    :paragraph-3 "Modifica el query para usar author-ids como una entrada al query para obtener el "
                    :paragraph-3.1 "nombre"
                    :paragraph-3.2 " y "
                    :paragraph-3.3 "apellido"
                    :paragraph-3.4 " de ambos autores."
                    :paragraph-4 "Puedes continuar al nivel 10"}}
