:level-12 {:english {:level-title "Level 12"
                     :paragraph-1 (str "Human " applicant-name ", the ")
                     :paragraph-1.1 ":xform"
                     :paragraph-1.2 " option provides the ability to transform the value returned by pull for an attribute."
                     :paragraph-2 "For example, if instead of an integer for \"expired batteries\" associated with a given energy farm the requirement is to return a word :xform can be used."
                     :paragraph-3 "(defn int->str [i]\n  (case i\n        0 \"zero\"\n        1 \"one\"\n        2 \"two\"\n        3 \"three\"\n        \"I have been advised not to talk numbers\"))\n\n(d/q '[:find  (pull ?farm [:farm/name [:farm/expired-battery-count :xform ns/int->str]])\n       :where [?farm :farm/name]]\n     db)"
                     :paragraph-5 "Using :xform update the query to return the "
                     :paragraph-5.1 ":user/first+last-name"
                     :paragraph-5.2 " of the post author and a string in the form of "
                     :paragraph-5.3 "Comment Count: <count>"
                     :paragraph-5.4 " for the "
                     :paragraph-5.5 ":post/comments"
                     :paragraph-6 "You may now continue to level 13."}
           :portuguese {:level-title "Nível 12"
                        :paragraph-1 (str "Humano " applicant-name ", a ")
                        :paragraph-1.1 ":xform"
                        :paragraph-1.2 " opção dá a habilidade de transformar o valor retornado pelo pull por um atributo."
                        :paragraph-2 "Por exemplo, ao invés de um número inteiro para \"expired batteries\" associadas a um determinado parque de energia, é possível usar o requisito :xform para retornar uma palavra."
                        :paragraph-3 "(defn int->str [i]\n  (case i\n        0 \"zero\"\n        1 \"one\"\n        2 \"two\"\n        3 \"three\"\n        \"Fui aconselhado a não falar números\"))\n\n(d/q '[:find  (pull ?farm [:farm/name [:farm/expired-battery-count :xform ns/int->str]])\n       :where [?farm :farm/name]]\n     db)"
                        :paragraph-5 "Usando :xform atualize a query para retornar para o "
                        :paragraph-5.1 ":user/first+last-name"
                        :paragraph-5.2 " do autor da postagem e uma string na forma de "
                        :paragraph-5.3 "Comment Count: <count>"
                        :paragraph-5.4 " para os "
                        :paragraph-5.5 ":post/comments"
                        :paragraph-6 "Você pode seguir para o nível 13."}
           :spanish {:level-title "Nivel 12"
                     :paragraph-1 (str "Humano " applicant-name ", la opción ")
                     :paragraph-1.1 ":xform"
                     :paragraph-1.2 " da la habilidad de transformar el valor regresado por PULL para un atributo."
                     :paragraph-2 "Por ejemplo, si en lugar de un entero para \"expired batteries\" asociadas con una granja de energía dada, el requirimiento fuera regresar una palabra, :xform podría ser usado. "
                     :paragraph-3 "(defn int->str [i]\n  (case i\n        0 \"zero\"\n        1 \"one\"\n        2 \"two\"\n        3 \"three\"\n        \"Me han aconsejado que no hable de números.\"))\n\n(d/q '[:find  (pull ?farm [:farm/name [:farm/expired-battery-count :xform ns/int->str]])\n       :where [?farm :farm/name]]\n     db)"
                     :paragraph-5 "Usando :xform en el query para regresar el "
                     :paragraph-5.1 ":user/first+last-name"
                     :paragraph-5.2 " del autor del post y un string con la forma "
                     :paragraph-5.3 "Comment Count: <count>"
                     :paragraph-5.4 " para los "
                     :paragraph-5.5 ":post/comments"
                     :paragraph-6 "Ahora puedes continuar al nivel 13."}}
