:level-select {:english {:zero "0. Prologue"
                         :one "1. Screening"
                         :two "2. The Basics"
                         :three "3. Multiple Variables"
                         :four "4. Unification"
                         :five "5. Pull"
                         :six "6. Reverse Lookup"
                         :seven "7. Pull Nested Values"
                         :eight "8. Parameterized Queries"
                         :nine "9. Collection Binding"
                         :ten "10. Aggregate Functions"
                         :eleven "11. Not"
                         :twelve "12. :xform"
                         :thirteen "13. Custom Functions"
                         :fourteen "14. Have A Seat"
                         :fifteen "15. The Exchange"
                         :sixteen "16. Looking Back"
                         :seventeen "17. You Can't Escape The Past"
                         :ninety-nine "99. Epilogue"}
               :portuguese {:zero "0. Prólogo"
                            :one "1. Triagem"
                            :two "2. O Básico"
                            :three "3. Múltiplas Variáveis"
                            :four "4. Unificação"
                            :five "5. Pull"
                            :six "6. Lookup Value"
                            :seven "7. Extrair Dados Aninhados"
                            :eight "8. Queries Parametrizadas"
                            :nine "9. Collection Binding"
                            :ten "10. Funções Agregadas"
                            :eleven "11. Não-Cláusulas"
                            :twelve "12. :xform"
                            :thirteen "13. Funções Customizadas"
                            :fourteen "14. Pegue uma Cadeira e Sente"
                            :fifteen "15. A Transação"
                            :sixteen "16. Olhando para Trás"
                            :seventeen "17. Você Não Pode Fugir do Passado"
                            :ninety-nine "99. Epílogo"}
               :spanish {:zero "0. "
                         :one "1. "
                         :two "2. "
                         :three "3. "
                         :four "4. "
                         :five "5. "
                         :six "6. "
                         :seven "7. "
                         :eight "8. "
                         :nine "9. "
                         :ten "10. "
                         :eleven "11. "
                         :twelve "12. :xform"
                         :thirteen "13. "
                         :fourteen "14. "
                         :fifteen "15. "
                         :sixteen "16. "
                         :seventeen "17. "
                         :ninety-nine "99. "}}
