:level-select {:english {:zero "0. Prologue"
                         :one "1. Screening"
                         :two "2. The Basics"
                         :three "3. Multiple Variables"
                         :four "4. Unification"
                         :five "5. Pull"
                         :six "6. Reverse Lookup"
                         :seven "7. Pull Nested Values"
                         :eight "8. Parameterized Queries"
                         :nine "9. Collection Binding"
                         :ten "10. Aggregate Functions"
                         :eleven "11. Not"
                         :twelve "12. :xform"
                         :thirteen "13. Custom Functions"
                         :fourteen "14. Have A Seat"
                         :fifteen "15. The Exchange"
                         :sixteen "16. Looking Back"
                         :seventeen "17. You Can't Escape The Past"
                         :ninety-nine "99. Epilogue"}
               :portuguese {}}
